In [2]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

In [48]:
import numpy as np

In [46]:
!pip install numpy

การลงนัมพาย


In [5]:
np.__version__

'1.19.5'

Vector or 1D Array

In [6]:
a = np.array([1,2,3,4,5,6,7])
a

array([1, 2, 3, 4, 5, 6, 7])

In [7]:
a[2:5]

array([3, 4, 5])

หาตำแหน่ง 2-5


In [8]:
a[:6]

array([1, 2, 3, 4, 5, 6])

ตั้งแต่ต้นจนถึงตำแหน่ง 6

In [9]:
a[3:]

array([4, 5, 6, 7])

ตั้งแต่ตำแหน่งที่ 3 จนสุด

In [10]:
a[-1]

7

ตำแหน่งสุดท้าย

In [11]:
a[-2]

6

ลองสุดท้าย

In [12]:
a[2:-3]

array([3, 4])

In [13]:
a[-5:]

array([3, 4, 5, 6, 7])

ถอยลงมา 5 ตำแหน่งแล้วรันไปถึงสุดท้าย

In [14]:
a[-5:-1]

array([3, 4, 5, 6])

In [15]:
np.size(a)

7

หาขนาดใน array


In [16]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [17]:
np.shape(a)

(3, 3)

## เช็ค Array 2D

In [18]:
a[0,0]

1

In [19]:
a[1,:]

array([4, 5, 6])

เรียกแถวที่ 1 ออกมาทั้งหมด

In [20]:
a[:,-1]

array([3, 6, 9])

เอาคอลั่ม


In [21]:
a[:,1] = 0 
a

array([[1, 0, 3],
       [4, 0, 6],
       [7, 0, 9]])

In [22]:
a[0:2,:] = 8
a

array([[8, 8, 8],
       [8, 8, 8],
       [7, 0, 9]])

In [23]:
np.size(a,1)

3

In [24]:
a.ndim

2

หาว่าข้อมูลมีกี่ไดแมนชั่น


In [25]:
np_mix_matrix = np.array([['one',2],['three',4],['five',6]])
np_mix_matrix

array([['one', '2'],
       ['three', '4'],
       ['five', '6']], dtype='<U5')

In [26]:

np.array(np_mix_matrix[:,1], dtype = int)

array([2, 4, 6])

In [27]:
a = np.zeros((2,2))
a

array([[0., 0.],
       [0., 0.]])

In [28]:
b = np.ones((2,2))
b

array([[1., 1.],
       [1., 1.]])

In [29]:
c = np.full((5,5),8)
c

array([[8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8]])

In [30]:
d = np.eye(5)
d

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [31]:
c*d

array([[8., 0., 0., 0., 0.],
       [0., 8., 0., 0., 0.],
       [0., 0., 8., 0., 0.],
       [0., 0., 0., 8., 0.],
       [0., 0., 0., 0., 8.]])

In [32]:
np.matmul(c,d)

array([[8., 8., 8., 8., 8.],
       [8., 8., 8., 8., 8.],
       [8., 8., 8., 8., 8.],
       [8., 8., 8., 8., 8.],
       [8., 8., 8., 8., 8.]])

In [33]:
np.sqrt(np.full((2,2),4))

array([[2., 2.],
       [2., 2.]])

In [34]:
a = [1,2,3,4,5,6,7,8,9,10]
np.random.choice(a,5)

array([2, 2, 8, 6, 5])

In [35]:
np_matrix = np.random.rand(5,5)
idx_choose = np.random.choice(5,3)
np_matrix_choose = np_matrix[idx_choose,:]
np_matrix_choose

array([[0.67643408, 0.95773506, 0.82554529, 0.13547346, 0.91468423],
       [0.37847601, 0.16785707, 0.19876393, 0.14758165, 0.6843922 ],
       [0.67643408, 0.95773506, 0.82554529, 0.13547346, 0.91468423]])

EX 2


In [36]:
np_matrix = np.random.rand(10,5)
np_matrix[:,4] = np.round(np.random.rand(1,10))
np_matrix

array([[0.70278754, 0.46861294, 0.34988958, 0.88744595, 1.        ],
       [0.827443  , 0.22094669, 0.97420449, 0.12080677, 0.        ],
       [0.11294755, 0.9968963 , 0.69527694, 0.72370428, 1.        ],
       [0.54516745, 0.19680372, 0.14678797, 0.89573872, 0.        ],
       [0.78314628, 0.08866484, 0.10380223, 0.20929138, 0.        ],
       [0.1262657 , 0.19878465, 0.62470019, 0.16007243, 0.        ],
       [0.88519421, 0.84490031, 0.64180212, 0.41914812, 0.        ],
       [0.79573472, 0.59633768, 0.8229323 , 0.12015537, 0.        ],
       [0.87197212, 0.00909313, 0.83837316, 0.78571951, 0.        ],
       [0.02961412, 0.98430574, 0.96170478, 0.0328016 , 1.        ]])

In [37]:
np_matrix = np.random.randint(11,size = (5,5))
np_matrix

array([[2, 2, 0, 6, 4],
       [0, 4, 0, 8, 9],
       [0, 2, 4, 9, 4],
       [6, 6, 1, 6, 9],
       [5, 4, 0, 6, 6]])

In [38]:
np_matrix = np.random.randint(3,size = (5,5))
np_matrix

array([[2, 1, 1, 1, 1],
       [1, 1, 1, 0, 1],
       [1, 1, 0, 1, 0],
       [0, 0, 1, 2, 2],
       [1, 0, 0, 1, 1]])

In [39]:
i,j = np.where(np_matrix == 2)

In [40]:
i

array([0, 3, 3])

j

In [41]:
j

array([0, 3, 4])

EX 3

In [42]:
idx = [1,2,3,4,5]
np_matrix[np.size(idx)-1,:]

array([1, 0, 0, 1, 1])

EX 4

In [54]:
matrix = np.random.randint(10,size=(10,5))
matrix

array([[5, 1, 2, 4, 6],
       [8, 8, 2, 8, 8],
       [0, 2, 9, 0, 6],
       [0, 2, 4, 9, 0],
       [1, 7, 7, 8, 4],
       [5, 0, 7, 0, 4],
       [1, 0, 1, 8, 6],
       [2, 8, 0, 5, 0],
       [1, 0, 1, 7, 2],
       [6, 0, 5, 6, 2]])

In [55]:
vector = np.random.randint(2,size=10) 
vector

array([0, 1, 0, 1, 0, 0, 1, 1, 1, 0])

In [53]:
matrix[np.where(vector == 0)]

array([[6, 3, 7, 6, 7],
       [3, 3, 1, 8, 7],
       [2, 1, 6, 8, 7],
       [8, 9, 4, 3, 2],
       [8, 6, 8, 4, 5],
       [2, 5, 3, 9, 4],
       [4, 3, 8, 8, 8],
       [1, 7, 0, 0, 9],
       [3, 8, 4, 7, 0],
       [5, 2, 2, 7, 4]])

In [56]:
matrix[np.where(vector == 1)]

array([[8, 8, 2, 8, 8],
       [0, 2, 4, 9, 0],
       [1, 0, 1, 8, 6],
       [2, 8, 0, 5, 0],
       [1, 0, 1, 7, 2]])