In [2]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

In [3]:
import numpy as np

In [4]:
!pip install numpy

การลงนัมพาย


In [5]:
np.__version__

'1.19.5'

Vector or 1D Array

In [6]:
a = np.array([1,2,3,4,5,6,7])
a

array([1, 2, 3, 4, 5, 6, 7])

In [7]:
a[2:5]

array([3, 4, 5])

หาตำแหน่ง 2-5


In [8]:
a[:6]

array([1, 2, 3, 4, 5, 6])

ตั้งแต่ต้นจนถึงตำแหน่ง 6

In [9]:
a[3:]

array([4, 5, 6, 7])

ตั้งแต่ตำแหน่งที่ 3 จนสุด

In [10]:
a[-1]

7

ตำแหน่งสุดท้าย

In [11]:
a[-2]

6

ลองสุดท้าย

In [12]:
a[2:-3]

array([3, 4])

In [13]:
a[-5:]

array([3, 4, 5, 6, 7])

ถอยลงมา 5 ตำแหน่งแล้วรันไปถึงสุดท้าย

In [14]:
a[-5:-1]

array([3, 4, 5, 6])

In [15]:
np.size(a)

7

หาขนาดใน array


In [16]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [17]:
np.shape(a)

(3, 3)

## เช็ค Array 2D

In [18]:
a[0,0]

1

In [19]:
a[1,:]

array([4, 5, 6])

เรียกแถวที่ 1 ออกมาทั้งหมด

In [20]:
a[:,-1]

array([3, 6, 9])

เอาคอลั่ม


In [21]:
a[:,1] = 0 
a

array([[1, 0, 3],
       [4, 0, 6],
       [7, 0, 9]])

In [22]:
a[0:2,:] = 8
a

array([[8, 8, 8],
       [8, 8, 8],
       [7, 0, 9]])

In [23]:
np.size(a,1)

3

In [24]:
a.ndim

2

หาว่าข้อมูลมีกี่ไดแมนชั่น


In [25]:
np_mix_matrix = np.array([['one',2],['three',4],['five',6]])
np_mix_matrix

array([['one', '2'],
       ['three', '4'],
       ['five', '6']], dtype='<U5')

In [26]:

np.array(np_mix_matrix[:,1], dtype = int)

array([2, 4, 6])

In [27]:
a = np.zeros((2,2))
a

array([[0., 0.],
       [0., 0.]])

In [28]:
b = np.ones((2,2))
b

array([[1., 1.],
       [1., 1.]])

In [29]:
c = np.full((5,5),8)
c

array([[8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8]])

In [30]:
d = np.eye(5)
d

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [31]:
c*d

array([[8., 0., 0., 0., 0.],
       [0., 8., 0., 0., 0.],
       [0., 0., 8., 0., 0.],
       [0., 0., 0., 8., 0.],
       [0., 0., 0., 0., 8.]])

In [32]:
np.matmul(c,d)

array([[8., 8., 8., 8., 8.],
       [8., 8., 8., 8., 8.],
       [8., 8., 8., 8., 8.],
       [8., 8., 8., 8., 8.],
       [8., 8., 8., 8., 8.]])

In [33]:
np.sqrt(np.full((2,2),4))

array([[2., 2.],
       [2., 2.]])

In [36]:
a = [1,2,3,4,5,6,7,8,9,10]
np.random.choice(a,5)

array([5, 4, 2, 5, 1])

In [40]:
np_matrix = np.random.rand(5,5)
idx_choose = np.random.choice(5,3)
np_matrix_choose = np_matrix[idx_choose,:]
np_matrix_choose

array([[0.89202041, 0.08301695, 0.428714  , 0.9962013 , 0.30869781],
       [0.89202041, 0.08301695, 0.428714  , 0.9962013 , 0.30869781],
       [0.24968735, 0.55965673, 0.99853827, 0.65660179, 0.29681966]])

EX 2


In [43]:
np_matrix = np.random.rand(10,5)
np_matrix[:,4] = np.round(np.random.rand(1,10))
np_matrix

array([[0.7575026 , 0.31922579, 0.96133697, 0.10116281, 0.        ],
       [0.59984691, 0.28442286, 0.35141299, 0.95774506, 1.        ],
       [0.31381798, 0.59673994, 0.52889963, 0.21324814, 0.        ],
       [0.62826112, 0.79195433, 0.84907852, 0.57855981, 1.        ],
       [0.87581973, 0.17796138, 0.80936287, 0.48738417, 1.        ],
       [0.84759332, 0.98748273, 0.11373289, 0.07437431, 0.        ],
       [0.39579786, 0.00202032, 0.19901731, 0.96869236, 1.        ],
       [0.37176143, 0.60889761, 0.29343874, 0.98553535, 1.        ],
       [0.31650266, 0.19374855, 0.34098581, 0.88428125, 1.        ],
       [0.24723181, 0.63271494, 0.28343199, 0.51098895, 0.        ]])

In [44]:
np_matrix = np.random.randint(11,size = (5,5))
np_matrix

array([[ 4, 10,  9,  2,  3],
       [ 6,  8,  4,  4,  0],
       [ 1,  9,  6, 10, 10],
       [ 6,  1,  6,  2,  6],
       [ 1,  2,  6,  0,  3]])

In [45]:
np_matrix = np.random.randint(3,size = (5,5))
np_matrix

array([[1, 2, 0, 0, 0],
       [0, 0, 1, 2, 2],
       [0, 2, 1, 0, 2],
       [0, 2, 1, 0, 2],
       [2, 2, 2, 2, 2]])

In [46]:
i,j = np.where(np_matrix == 2)

In [47]:
i

array([0, 1, 1, 2, 2, 3, 3, 4, 4, 4, 4, 4])

j

In [48]:
j

array([1, 3, 4, 1, 4, 1, 4, 0, 1, 2, 3, 4])

EX 3

In [50]:
idx = [1,2,3,4,5]
np_matrix[np.size(idx)-1,:]

array([2, 2, 2, 2, 2])

EX 4

In [56]:

matrix = i.randint(10 ,size=(10,5))
matrix

array([[9, 0, 2, 0, 7],
       [1, 7, 9, 8, 4],
       [0, 1, 9, 8, 2],
       [3, 1, 2, 7, 2],
       [6, 0, 9, 2, 6],
       [6, 2, 7, 7, 0],
       [6, 5, 1, 4, 6],
       [0, 6, 5, 1, 2],
       [1, 5, 4, 0, 7],
       [8, 9, 5, 7, 0]])